### ISSUE TITLE
Horizontal scrolling bug

### ISSUE THREAD

**Issue by devmaximilian** [Beyarz/lines#2]
I have only tested this on a smartphone. It appears as if I'm able to scroll horizontally on the page.

Is this intended or could it be a bug? See attached screenshot.

![E1A02A8D-D72F-44D7-BAEA-094C1BC412AF](https://user-images.githubusercontent.com/16129610/68082843-0489e580-fe22-11e9-8aa6-96b856b7d96e.jpeg)

**Comment by Beyarz** [comment]
Fixed https://github.com/Beyarz/lines/commit/d4613882c76334066aae7bd4907a0cfda741ff6b
